### ISSUE TITLE
Cannot run graphical apps on Wayland

### ISSUE THREAD

**Issue by RolandWH** [slicer69/doas#44]
Doas cannot seam to run graphical apps on Wayland (have not tested on X11/Xorg yet). I have attached a screenshot below. 
![Doas graphical apps error](https://user-images.githubusercontent.com/45169084/95980375-f9eb1500-0e14-11eb-9c88-92fb29614f98.png)

OS: Arch Linux
Kernel: 5.8.14-zen
GPU: AMD RX 5700

**Comment by slicer69** [comment]
This a feature of Wayland. As I understand it you're not supposed to be able to run desktop applications as root on Wayland without some workarounds. See this conversation: https://bbs.archlinux.org/viewtopic.php?id=247088

This is why so many desktop applications are moving away from running as root and only prompting for admin access to perform specific tasks. This isn't a doas limitation.

**Comment by RolandWH** [comment]
This is strange as using sudo doesn't give any issues. Maybe they implemented those workarounds?

**Comment by slicer69** [comment]
Possibly. Or it could be that you've got XWayland installed and it's providing a compatibility layer in which case sudo isn't actually working with Wayland, it's effectively running on X11. In which case I'd also like to confirm that keepenv is enabled in the doas.conf file? If not then no graphical applications will run, on X11 or Wayland. From the doas.conf manual page:

"Note: In order to be able to run most desktop (GUI) applications, the user needs to have the keepenv keyword specified. If keepenv is not specified then key elements, like the user's $HOME variable, will be reset and cause the GUI application to crash."

**Comment by RolandWH** [comment]
Thank you this was the issue. I added keepenv to my config and it all worked fine on wayland.
