### ISSUE TITLE
doas: not installed setuid - macOS 11.1

### ISSUE THREAD

**Issue by burnsac5040** [slicer69/doas#60]
I have installed xcode command line tools and used:
- `make`, `make install`
- `make`, `sudo make install`

I then installed make from homebrew and used:
- `gmake`, `gmake install`
- `gmake`, `sudo gmake install`

On both of these I get the error: `doas: not installed setuid`
I get this error when running `vidoas`: `install: /usr/local/etc/doas.conf: chown/chgrp: Operation not permitted`.

I've also tried creating `doas.conf` using `sudo` by running `sudo nvim /usr/local/etc/doas.conf` as well as `sudo vidoas`.

Is there anything that I am doing wrong? Perhaps I need to disable System Integrity Protection (SIP) for this to work? Or should I changed the prefix of the makefile to install to `/usr/` instead of `/usr/local/`?

**Comment by slicer69** [comment]
I can't be sure because I don't use macOS and can't support it. However, I can tell you that vidoas needs to be run as the root user (or using a tool like sudo or doas). This is mentioned in the script's manual page.

As for the install process, I'm not sure what is going wrong there, but it looks like something is blocking doas from being set up to run as root (setuid). My guess it you may need to manually change it using "sudo chmod 4755 /usr/local/bin/doas".

I would definitely not move the prefix to another location. The location shouldn't make any difference.

By the way, another macOS user posted recently and mentioned that homebrew sets up directories in /usr/ to be writable by the user. If your system does this it is a huge security issue as it means anyone can replace your doas binary or doas.conf file with their own and run any command as root. Make sure your directories are not writable by your user before you install doas.

**Comment by burnsac5040** [comment]
This can be closed now.  I changed permissions and everything earlier but never got it to work out.  All I did was run `sudo make`, `sudo make install` instead of `make`, `sudo make install` and it works fine now!
