### ISSUE TITLE
vidoas: linux: how can i change the default editor of vidoas, could not open config file when running vidoas

### ISSUE THREAD

**Issue by cindrmon** [slicer69/doas#62]
Good Morning!

I have two issues with vidoas.

1. **for the editor issue**, it states that i don't have a default editor, despite me editing the environment variable for the default editor being vim. Another issue i had is when I tried doing the same command, with the `EDITOR=vim` written before vidoas, and it doesn't let me. Why doesn't it recognize my editor environment file?
2. **for the vidoas script itself**, it states that it couldn't open config file `/tmp/doas.conf: No such file or directory`, and then i have to fix doas.conf. what should i do at this point? Do I start over with the doas.conf file?

For additional information, this is the output when running `doas vidoas`:
```
➤ doas vidoas
Password: 
No default editor, assuming vi.
doas: could not open config file /tmp/doas.conf: No such file or directory
An error was found in the configuration file. Please fix doas.conf.
```

This is the second output when running `doas EDITOR=vim vidoas`:
```
➤ doas EDITOR=vim vidoas
Password: 
doas: EDITOR=vim: command not found
```

Thank you for your support.

**Comment by slicer69** [comment]
Okay, three things are happening here, one of them really not good. The issue with the EDITOR variable is easy, the variable declaration needs to go before the command you are running, not after. The command

     doas EDITOR=vim vidoas

Tells doas to run the command "EDITOR=vim". What you want is

    EDITOR=vim doas vidoas

Following up on that, doas drops environment variables by default. If you want to set environment variables that will survive in the doas environment, make sure your user has the keepenv flag set in the doas.conf file. The doas.conf manual page has details on this.

Finally, your build of doas somehow forced the program's PREFIX to be /tmp by the looks of things, which is why doas is looking for its configuration file at /tmp/doas.conf. This should never, ever happen. If that's right it means either you specified /tmp as your prefix at compile time (which shouldn't be done) or your shell has a PREFIX variable set to /tmp instead of somewhere reasonable like /usr/local, which also shouldn't happen.

My advice is: 1. Recompile doas and make sure PREFIX is set properly. 2. Make sure keepenv flag is set in your doas.conf file. 3. Place environment variables before commands in the shell.
