### ISSUE TITLE
doas unresponsive after reboot

### ISSUE THREAD

**Issue by Mithrandir2k18** [slicer69/doas#65]
I just installed doas, trying it out as an alternative for sudo.

I followed the installation guide and it all seemed to work flawlessly. I aliased sudo to doas, uninstalled sudo and rebooted the pc.

Now when I call doas, terminal just stops and waits. I can interrupt out of it, but it doesn't execute anything it seems.

What's the problem here? Does doas need sudo to work?

**Comment by slicer69** [comment]
No, doas does not need sudo to work. It does however need PAM on most platforms.

You didn't tell me anything about your OS or setup, but my guess is that when you removed sudo it also removed dependencies that sudo uses. Some PAM modules get installed by sudo on some platforms that doas uses. So if you installed doas from source (ie not using your package manager) and then removed sudo which removed related PAM modules, then doas would stop working.

This means your package manager either removed dependencies or your OS's PAM modules broke when you removed sudo, maybe due to a config change. So bottom line is doas doesn't need sudo, but it probably needs PAM on your platform and removing sudo probably broke part of your PAM setup.

**Comment by Mithrandir2k18** [comment]
Oh yes, sorry. I am on an up-to-date version of Ubuntu 20.04.

Which modules are required? Also that's weird because apt removed sudo without a hitch and afterwards doas still worked normally. Are the modules only unloaded aftet a reboot?

**Comment by slicer69** [comment]
I'm not sure as I don't use Ubuntu. However, not having the modules unloaded out of memory until a reboot would seem typical.

I forget which system, maybe macOS, we found to get doas running we needed a /etc/pam,d/doas module file that contained the same lines as the sudo module would. For example, on  my distro machine the /etc/pam.d/doas file contains the following four lines. You might need to make this text file and restart:

#%PAM-1.0
@include common-auth
@include common-account
@include common-session-noninteractive

**Comment by Mithrandir2k18** [comment]
Just reinstalled sudo and rebooted. sudo is back and works, but doas still behaves the same. There might be something different going wrong. Here's my `uname -a` output:

`Linux atgrzln310018 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by slicer69** [comment]
PAM configuration is something which should be brought up with your distro's support forum or mailing list.
