### ISSUE TITLE
FreeBSD port: `vidoas` script has wrong default `doas.conf` file path

### ISSUE THREAD

**Issue by abakay** [slicer69/doas#81]
I am running FreeBSD 12.2. After `doas` installation `pkg install doas`, the `vidoas` script has wrong default path to `doas.conf` file: `DOAS_CONF=@DOAS_CONF@`.

**Comment by slicer69** [comment]
Sounds like something went wrong with the port. 

Update: Just checked and confirmed the port still tries to copy the original vidoas script onto the system instead of the one where the DOAS_CONF variable has been set. I'll send them a patch to fix it.

You can either install doas from source here to fix it or just edit doas.conf by hand until the FreeBSD port collection gets fixed.

**Comment by abakay** [comment]
Ok, thanks for quick response!

**Comment by slicer69** [comment]
I've uploaded a patch for the FreeBSD port. It should be corrected in a few days to a week, based on past commit time.

**Comment by slicer69** [comment]
This fix has been accepted upstream. If you build the port now, or install the FreeBSD package for version 6.3p5 then vidoas should work properly.
