### ISSUE TITLE
using 'nopass' still asking for password

### ISSUE THREAD

**Issue by ltsdw** [slicer69/doas#83]
I probably reading the doc wrongly, but here is an example that I have at doas.conf:
`permit nopass little as root cmd "/usr/bin/systemctl restart bluetooth"`

when running `systemctl restart bluetooth` or `doas systemctl restart bluetooth` it's still asking for password.

Also there is a problem (well I don't know if it is a problem, but the examples of the doas.conf doesn't shows it with quotation marks) that if I don't surround the command that has arguments with quotation marks (""), the doas will show that there's a syntax error at the specific line. So for example if I have `permit nopass little as root cmd /usr/bin/systemctl restart bluetooth` doas will complain about a syntax error.

`doas: syntax error at line 1`

**Comment by slicer69** [comment]
doas is asking for a password because the command in the doas.conf file doesn't match the one on the command line. "/usr/bin/systemctl" is different from "systemctl". So you'd need to either change the doas.conf file to match or use the full path name on the command line.

As for the latter problem with quote marks, I haven't been able to reproduce that one. I don't use quotes in my doas.conf file and it runs commands, with and without arguments. Is it possible there is a special character or a tab in the line?

**Comment by ltsdw** [comment]
> doas is asking for a password because the command in the doas.conf file doesn't match the one on the command line. "/usr/bin/systemctl" is different from "systemctl". So you'd need to either change the doas.conf file to match or use the full path name on the command line.
@slicer69 

I just tested with both `/usr/bin/systemctl restart bluetooth` and `systemctl restart bluetooth` the result is the same.
Also tested with `permit nopass little as root cmd pacman -Syu`, and running `doas pacman -Syu` still prompts for a password, running the command without the doas as prefix will say that I need to run it as root.

> As for the latter problem with quote marks, I haven't been able to reproduce that one. I don't use quotes in my doas.conf file and it runs commands, with and without arguments. Is it possible there is a special character or a tab in the line?

negative, it's is a plain file, with 2 lines in it.
let me post the entire content here maybe I'm doing something wrong.

```
permit keepenv :wheel
permit nopass little as root cmd "/usr/bin/systemctl restart bluetooth"
```

If I change `permit keepenv :wheel` to `permit keepenv nopass :wheel`, in fact I can run any command without needing to enter a password, but I only need that to a specific command.

**Comment by slicer69** [comment]
I will look into this further. First though could you tell me how you installed doas on your system? It looks like you're running Arch Linux (or a member of the Arch family). Did you install doas from source yourself, from a AUR entry (if so which one, please), from an official repository?

**Comment by ltsdw** [comment]
Sure, installed through `paru doas`, this package over here [doas](https://aur.archlinux.org/packages/doas/). And yes, I'm running arch.

**Comment by slicer69** [comment]
I may have figured out what is happening here. doas (plain, vanilla doas) defaults to looking for its configuration file at /usr/local/etc/doas.conf. However, it looks like the AUR script patches the Makefile to relocate the configuration file to /etc/doas.conf. However, I don't think the patched Makefile used in the AUR defines the new location properly.

In the altered version of the Makefile the AUR build uses CFLAGS is defined as "CFLAGS+=-D_GNU_SOURCE", but it should be something more like this: "CFLAGS+=-D_GNU_SOURCE Wall $(OPT) -DUSE_PAM -DDOAS_CONF=\"$(DOAS_CONF)\" $(TARGETPATH)"

The key part is the DOAS_CONF bit which tells doas where to find its configuration file.

So I suspect what is happening is doas is looking in the wrong place on your system for the configuration file. It may even be reading the default configuration file provided by the AUR build posted here: https://aur.archlinux.org/cgit/aur.git/tree/doas.conf?h=doas

That default config file allows anyone to run commands as root, but doas would always ask for a password. I suspect your system is using the default doas.conf file offered by the AUR build and ignoring the one you have created, which would explain why doas is not respecting the "nopass" flag in your version of the file.

Short term you can probably fix this by installing doas from its source code and using the default configuration file /usr/local/etc/doas.conf. (Assuming I've correctly guessed what the problem is.) Long term someone should fix the AUR build for doas as it looks like anyone that installs it will end up with a misconfigured version of doas.

**Comment by ltsdw** [comment]
mmm... I don't know, got the source with git clone, compiled and installed, tested that the configuration file at `/usr/local/etc/doas.conf` is in fact taking effect, but the same behaviour still (the quotation one, and the major one)...

I don't know if it's relevant, but here is the `/etc/pam.d/doas` content:

```
#%PAM-1.0
auth	sufficient	pam_fprintd.so
auth	include		system-auth
account	include		system-auth
session	include		system-auth
```

**Comment by ltsdw** [comment]
In addition, there's something interest, like if I run:

```
$ doas -C /usr/local/etc/doas.conf pacman -Syu
permit
```

and

```
$ doas -C /usr/local/etc/doas.conf "pacman -Syu"
permit nopass
```

I think the probably maybe is the quotation mark? If that is the case, so there's a problem, if I remove the quotation then I get a sintax error (also tried deleting the file and using the vidoas to edit it, the result is the same).

**Comment by ltsdw** [comment]
Nvm, I just need to run it as `doas systemctl restart bluetooth`, but it will only work if I specify at doas,conf, as like: `permit nopass little as root cmd systemctl` without quotation and any flag.

But then the systemctl will not ask for password for other uses and service...  the same applies for pacman, I cannot specify for example only to run it with -Syu flag, only works if I just put the plain command as `permit nopass little as root cmd pacman`. Being possible to run pacman -R flag and any other, for example.

Any ideas as to work for specific use case?

**Comment by slicer69** [comment]
Have you tried using the "args" keyword? Typically if you're planning to match a command and parameters you'd use the args keyword like this:

      permit nopass little as root cmd pacman args -Syu

or

     permit nopass little as root cmd systemctl args restart bluetooth

**Comment by ltsdw** [comment]
Aha! that did the trick, thank you!
And it's mentioned here [doas.conf.sample](https://github.com/slicer69/doas/blob/master/doas.conf.sample) I should looked up better.
