### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by wizard-28** [slicer69/doas#93]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/594) to add `doas-git` to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation of Doas for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by slicer69** [comment]
Thanks for getting in touch.

With regards to the first question about maintaining the Pacstall script, I'd like to avoid getting involved with platform/repo specific package maintenance. I'm happy to work with downstream maintainers to make their lives easier. I'm happy to consider patches that make building downstream easier. 

However, since doas runs on dozens on Linux distributions and about half a dozen other platforms I feel my trying to maintain it everywhere would quickly become a problem.

Regarding the second question about updating the documentation for Debian/Ubuntu to include Pacstall install instructions, I will be happy to accept a pull request for this. I know Debian/Ubuntu have an OpenDoas package, but I don't think they have a doas package for this project yet so having install instructions for Pacstall will be useful for the community.
